### PR TITLE
Feature/carousels

### PR DESCRIPTION
**Pull request by ajmcnall**
A plugin, requested by the agency, for more easily creating carousels in the studio using tags

### CODE REVIEW

**Comment by SamJacobs** [comment]
@brettdavidson3 were you helping andy with this? what happened to it?

**Comment by brettdavidson3** [comment]
It needs review. I'm not sure I'm the best person to review it because I was pairing with Andy for some of it.

**Comment by SamJacobs** [comment]
@tommydarko do you know anything about this code? do we need to get this reviewed and tested?

**Comment by brettdavidson3** [comment]
This is pretty old and I believe is solved by Smartbags™️ . I'll leave the branch around in case we want to come back to it.

**Pull request closed without merging**
