### PR TITLE
Resolves #8

### LINKED ISSUE #8: SDK BUG: Readme has wrong URL for soundjs
Currently points at v1 and should point at v0. 
Also it should not be gz

//sdk.ceros.com/soundjs/main-v0.js

### PR DESCRIPTION
**Pull request by brianpabent**
Resolves #8 

Removed GZ from example urls because the CDN will auto-gzip. yay.
Also, set SoundJS plugin to v0

### CODE REVIEW

**Comment by brianpabent** [comment]
Please Review

**Comment by addelong** [comment]
Looks good 👍

**Comment by danwashable** [comment]
I think this can just merge. There's no code changes. Just a README change.

**Comment by danwashable** [comment]
@brianpabent Any reason not to merge this?

**Pull request merged**
